# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4fcf0cd862eafd13af987ddbad9470acb946182ad130f84270aa6af7962c9bb60c5b3303cb1fc2053dfb169154e2ec86092181071825cc6721dcbe47b9cb29

test:
  secret_key_base: 6c7ffe3f2d995e8884a1dbc996c4fe1e012abd7834f3e759be9ba5c528d8a2b9c5af07056eb5c9b83c4ffb1f4bc191f684c305b1c66c28b7b9a240831401964c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
